name: Skellett
author: LimeGlass
description: The addon with the beast name
version: 1.4.5
main: com.gmail.thelimeglass.Main
depend: [Skript]
softdepend: [OneInTheBattle, BungeeBridge, GuardianBeamAPI]